### ISSUE TITLE
Website URL on GitHub profile

### ISSUE THREAD

**Issue by szepeviktor** [jlondiche/jlrecrutement#15]
Please consider fixing the URL on your profile https://github.com/jlondiche
jlrecrutement.com 👉🏻 www.jlrecrutement.com

The non-www version (provided by gandi.net) does not support HTTPS 🔐

**Comment by jlondiche** [comment]
Hello @szepeviktor ! I don't really understand what you mean ?

**Comment by szepeviktor** [comment]
On your GitHub profile you have the non-www version

![image](https://user-images.githubusercontent.com/952007/227506540-a1c54f48-3f64-4b60-9876-309f9957fc85.png)

Someone clicks on that link and navigates to a website without HTTPS, without encryption.
Then gets redirected to https://www.jlrecrutement.com/

If you change your website URL on your GitHub profile to `https://www.jlrecrutement.com` all traffic will be secure, encrypted 🔒

**Comment by jlondiche** [comment]
Hello @szepeviktor, je n'arrive plus à mettre à jour le readme de mon github depuis ton update sur le NOUVEAU. Peux-tu m'aider ? Par avance, un grand merci !

**Comment by szepeviktor** [comment]
Je peux vous aider 🇫🇷 
But only in English :(

![image](https://user-images.githubusercontent.com/952007/229163490-128fd29b-41e4-477f-930d-b8bad9cae1ab.png)

This issue is about your GitHub profile, not https://github.com/jlondiche/jlrecrutement nor https://github.com/jlondiche/job-board-php

Just click on the Edit button

![image](https://user-images.githubusercontent.com/952007/229163843-30eb3765-0e6c-4f17-b6ee-82ac13614166.png)

And change `jlrecrutement.com` to `https://www.jlrecrutement.com`
