### ISSUE TITLE
HTTPS should be enforced

### ISSUE THREAD

**Issue by ErikSaunier** [jlondiche/jlrecrutement#6]
Your site is loading correctly over HTTPS but you should enforce HTTPS in your repository’s settings for users who request your site over HTTP. This will make them be upgraded to HTTPS.

![](https://blog.github.com/assets/img/2018-05-01-github-pages-custom-domains-enforce-https.png)

1. On GitHub, navigate to the main page of the repository.
2. Under your repository name, click **Settings**.
3. Under "GitHub Pages," select **Enforce HTTPS**.

Information found here:
[Enforcing HTTPS for your GitHub Pages site](https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site)

Bonus:
[Lemon & Kiwi](https://lemon-kiwi.co)

**Comment by jlondiche** [comment]
@adipasquale ?

**Comment by ErikSaunier** [comment]
After **enforcing HTTPS**, [http://www.jlrecrutement.com](http://www.jlrecrutement.com) should by redirected to [https://www.jlrecrutement.com](https://www.jlrecrutement.com)

**Comment by adipasquale** [comment]
@ErikSaunier @jlondiche not sure how I completely missed that for so long .. sorry ! I just went ahead and fixed my GitHub notification settings.

This issue doesn't seem to be fixed yet, http still doesn't redirect to https. @jlondiche can you activate the settings option rightly pointed out by @ErikSaunier ? You're the repo owner, and as such you're the only one who can set it.

**Comment by jlondiche** [comment]
Done.
Thanks a lot @ErikSaunier & @adipasquale and happy new year :)

**Comment by ErikSaunier** [comment]
Well done @jlondiche 🚀
